title: XMLua
markdown: kramdown
highlighter: rouge
version: 1.2.1
release_date: 2023-02-03
exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
description:
  en: Easy to use HTML and XML library for Lua
  ja: 使いやすいLua用のHTML・XML処理ライブラリー

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: assets/stylesheets

defaults:
  - scope:
      path: "ja"
    values:
      path_prefix: /ja/
      layout: "base"
      language: ja
      country: JP
  - scope:
      path: ""
    values:
      path_prefix: /
      layout: "base"
      language: en
      country: US
