name: macOS
on:
  - push
  - pull_request
jobs:
  macos:
    name: Test
    strategy:
      fail-fast: false
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install XMLua
        run: |
          brew update
          brew bundle
          LUAROCKS="sudo -H luarocks --tree=$(brew --prefix) --lua-dir=$(brew --prefix luajit)"
          VERSION=$(grep VERSION xmlua.lua | sed -e 's/.*"\(.*\)"/\1/g')
          cp xmlua.rockspec xmlua-${VERSION}-0.rockspec
          ${LUAROCKS} make xmlua-${VERSION}-0.rockspec LIBXML2_DIR=$(brew --prefix libxml2)
          rm -rf xmlua.lua xmlua
          ${LUAROCKS} install luaunit
          ${LUAROCKS} install cqueues \
            CRYPTO_DIR=$(brew --prefix openssl) \
            OPENSSL_DIR=$(brew --prefix openssl)
          git clone --depth 1 https://github.com/clear-code/luacs.git ../luacs
      - name: Test
        run: |
          test/run-test.lua
          luajit -e 'package.path = "../luacs/?.lua;" .. package.path' \
            sample/parse-html-cqueues-thread.lua sample/sample.html
